variable "resource_group_name" {}
variable "location" {}
variable "address_space" {}
variable "virtual_network_name" {}
variable "subnet_names" {}
variable "subnet_address_ranges" {}
variable "frontend_ip_configuration_name" {}
variable "allocation_method" {}
variable "azurerm_lb_name" {}
variable "azurerm_lb_backend_address_pool_name" {}