variable "azurerm_resource_group" {}
variable "address_space" {}
variable "azurerm_virtual_network" {}
variable "name" {}
variable "resource_group_name" {}
variable "location" {}
variable "tags" {}
variable "address_prefixes" {}
variable "azurerm_linux_virtual_machine_scale_set_name" {}
variable "sku_size" {}
variable "instances" {}
variable "admin_username" {}
variable "username" {}
variable "azurerm_subnet" {}
